name: finance_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  syncfusion_flutter_pdf: ^24.1.41

  #UI + Animations
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2

  # Firebase (latest compatible versions for Dart 3)
  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

  # Utilities
  intl: ^0.19.0
  fl_chart: ^0.68.0
  uuid: ^4.5.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
